<?php

namespace CarnetAdressesAppartoo\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use CarnetAdressesAppartoo\UserBundle\Entity\User;


/**
 * AddressBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressBookRepository extends EntityRepository {
    
    public function findAddressBookOf(User $user) {
        $builder = $this->createQueryBuilder('ab');
        $builder->where('ab.owner = :owner')
                ->setParameter('owner', $user);
        
       return $builder->getQuery()->getOneOrNullResult();
    }
	
}